#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
  ll="ls -l" \
  la="ls -a" \
  l="ls -al" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	z="zathura"

alias cx="chmod +x"
alias open=xdg-open
alias curl="curl --user-agent 'noleak'"
alias wget="wget -c --user-agent 'noleak'"
alias shred="shred -zf"
alias sz="source ~/.zshrc"
alias lf=lfub

# human friendlly
alias df="df -h"
alias free="free -h"
alias du="du -h"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"
alias dd="dd status=progress"

se() { cd ~/.local/bin; $EDITOR $(fzf) ;}
