-- docs keymap descriptions for which-key
local wk = require('which-key')
wk.register({
  ["<leader>"] = {
    f = {
      name = "+finders",
      a = "TS search aerial",
      f = "TS search files",
      g = "TS live grep",
      o = "TS old files",
      b = "TS search buffers",
      h = "TS help tags",
      r = "RG ripgrep",
    },
    d = {
      name = "+debug",
      d = "continue",
      l = "run last",
      u = "ui",
      b = "breakpoint with message",
      o = "repl open",
      h = "hover",
      p = "preview",
      f = "frames",
      s = "scopes",
      ["-"] = "F6-F9:",
      ["<F6>"] = "breakpoint toggle",
      ["<F7>"] = "step over",
      ["<F8>"] = "step into",
      ["<F9>"] = "step out",
    },
    e = "diagnostic float info",
    q = "diagnostic telescope",
    h = {
      name = "+hunk options",
      t = {
        name = "+toggle",
        d = "toggle deleted",
        b = "toggle line blame",
      },
    },
    l = {
      name = "+lsp options",
      r = "lsp rename",
      a = "lsp code actions",
      f = "lsp format",
    },
    u = "undo tree toggle",
    m = "markdown preview",
    s = {
      name = "+scripts,snippets",
      v = "vsnip vsplit edit",
      y = "vsnip yank",
    },
    r = {
      name = "+run",
      c = "compiler",
      r = "compiler < inp",
      n = "rename",
    },
    w = {
      name = "+wiki, workspace",
      i = "VimWiki diary index",
      t = "VimWiki table index",
      w = "VimWiki index",
      s = "VimWiki select",
      a = "add workspace",
      l = "list workspace",
      r = "remove workspace",
      ["<space>"] = {
        name = "+wiki util",
        i    = "DiaryGenerateLinks",
        y    = "MakeYesterdayDiaryNote",
        m    = "MakeTomorrowDiaryNote",
        t    = "TabMakeDiaryNote",
        w    = "MakeDiaryNote",
      }
    },
    ["["] = "prev tab",
    ["]"] = "next tab",
    [";"] = "quick add ;",
    [","] = "prev buffer",
    ["."] = "next buffer",
  },
  g = {
    name = "+goto",
    D = "go to declaration",
    d = "go to definition",
    t = "go to type definition",
    I = "go to implementation",
    r = "go to references",
    C = "go to context",
  },
  ["["] = {
    name = "+prev",
    ["%"] = "prev unmatched group",
    ["("] = "prev (",
    ["<"] = "prev <",
    ["{"] = "prev {",
    ["]"] = "prev function start",
    ["<space>"] = "add blank line up",
    A = "first file",
    a = "prev file",
    B = "first buffer",
    b = "prev buffer",
    c = "prev hunk",
    d = "prev diagnostic",
    e = "move line up",
    i = "prev conditional",
    z = "prev fold",
    p = "prev parameter",
  },
  ["]"] = {
    name = "+next",
    ["%"] = "next unmatched group",
    ["("] = "next (",
    ["<"] = "next <",
    ["{"] = "next {",
    ["]"] = "next function start",
    ["<space>"] = "add blank line down",
    A = "last file",
    a = "next file",
    B = "last buffer",
    b = "next buffer",
    c = "next hunk",
    d = "next diagnostic",
    e = "move line down",
    i = "next conditional",
    z = "next fold",
    p = "next parameter",
  },
  [","] = {
    name = "+terminals",
    [","] = "focus back",
    n = "new terminal in current buffer directory",
    s = "floaterm send",
    t = "floaterm toggle",
  },
})
