#!/bin/zsh
# profile file. Runs on login. Environmental variables are set here.

export MAKEFLAGS="-j $(grep processor /proc/cpuinfo | wc -l)"
export LANG=en_US.UTF-8
export TIME_STYLE='+%y/%m/%d %H:%M:%S'
export HIST_STAMPS="yyyy-mm-dd"

unsetopt PROMPT_SP

# Default programs:
export EDITOR="nvim"
export TERMINAL="st"
export IMG_VIEWER="nsxiv"
export BROWSER="firefox"
export APPH=""
export APPJ=""
export APPK="code"

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export XAUTHORITY="$XDG_CONFIG_HOME/.Xauthority"
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME/notmuch-config"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
#export ALSA_CONFIG_PATH="$XDG_CONFIG_HOME/alsa/asoundrc"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export GOPATH="$XDG_DATA_HOME/go"
export VIMWIKI_DIR="$XDG_DATA_HOME/nvim/vimwiki"
export PYTHON_VENV_DIR=$HOME/.local/share/pyenv
# export BLOG_DIR="$HOME/foo/blog"
# for script uploadlast to upload lastd screenshot file to imgur
# export IMGUR_CLIENT_ID="foo"

# Other program settings:
export DICS="/usr/share/stardict/dic/"
export SUDO_ASKPASS="$HOME/.scripts/dmenupass"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"
export LESSOPEN="| /usr/bin/highlight -O ansi %s 2>/dev/null"
export QT_QPA_PLATFORMTHEME="gtk2"         # Have QT use gtk2 theme.
export MOZ_USE_XINPUT2="1"                 # Mozilla smooth scrolling/touchpads.
export AWT_TOOLKIT="MToolkit wmname LG3D"  # May have to install wmname
export _JAVA_AWT_WM_NONREPARENTING=1       # Fix for Java applications in dwm

# Adds `~/.local/bin` to $PATH
export PATH=$PATH:$HOME/.scripts:${$(find ~/.local/bin -type d -printf %p:)%%:}:$CARGO_HOME/bin:$GOPATH/bin

[ ! -f $XDG_CONFIG_HOME/shell/shortcutrc ] && shortcuts >/dev/null 2>&1 &

# Start graphical server on user's current tty if not already running.
[ "$(tty)" = "/dev/tty1" ] && ! pidof -s Xorg >/dev/null 2>&1 && exec startx "$XINITRC" > /dev/null 2>&1

# Switch escape and caps if tty and no passwd required:
sudo -n loadkeys $XDG_DATA_HOME/ttymaps.kmap 2>/dev/null
