#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

autostart="picom remaps clipmenud mpd dunst unclutter gammastep"

for program in $autostart; do
  pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# pulseaudio --kill;
pipewire &
# wireplumber &

# xresources set the colors to tokyo night and dpi
xrdb -merge $XDG_CONFIG_HOME/x11/xresources
~/.fehbg # set wallpaper
# wal -R # refresh pywal colors

ibus-daemon -drx
export GTK_IM_MODULE=ibus
export QT_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
