general {
    lock_cmd = pidof hyprlock || blurlock
    before_sleep_cmd = blurlock
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}

listener {
    timeout = 3600
    on-timeout = blurlock
}

listener {
    timeout = 3900
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "off" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "on" })'
}
