#!/bin/zsh

export PATH=/root/.scripts:/root/.local/bin:$PATH

# common options
export LANG=en_US.UTF-8
export TIME_STYLE='+%y/%m/%d %H:%M:%S'
export HIST_STAMPS="yyyy-mm-dd"

# export all_proxy="127.0.0.1:7890"

unsetopt PROMPT_SP

# Default programs:
export EDITOR="vim"
export TERMINAL="st"

# ~/ Clean-up:
export XAUTHORITY="/root/.config/.Xauthority" # This line will break some DMs.
export LESSHISTFILE="-"
export INPUTRC="/root/.config/shell/inputrc"
export FZF_DEFAULT_OPTS="--layout=reverse --height 40%"
export LESS=-R
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')"
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')"
export LESS_TERMCAP_me="$(printf '%b' '[0m')"
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')"
export LESS_TERMCAP_se="$(printf '%b' '[0m')"
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')"
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"

# Switch escape and caps if tty and no passwd required:
[ ! -f /root/.config/ttymaps.kmap ] && oadkeys /root/.config/ttymaps.kmap 2>/dev/null
