#!/bin/sh

# 1. pause all mpv sockets
for i in /tmp/mpvSockets/*; do
        [ -e "$i" ] || continue
        echo '{ "command": ["set_property", "pause", true] }' | socat - "$i";
done
# 2. pause ncmpcpp by mpc
mpc pause
# 3. pause web browser stuff
playerctl pause

# actual locker (hyprlock takes its own blurred screenshot)
exec hyprlock
