#!/bin/sh
option='Y'
read -p "Empty trash can? [Y]/n: " option
[ $option -e 'Y' ] && rm -rf $XDG_DATA_HOME/Trash/files

echo "Try to clear yay and pacman cache, password needed."
yay -Scc

option='Y'
read -p "Remove pip cache? [Y]/n: " option
[ $option -e 'Y' ] && pip cache purge
