#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extension or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.

# pipe file 'inp' into executable
echo
echo "--------------------*** output ***--------------------"
file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

case "$ext" in
  c) cc "$file" -o "$base" && "$base" < "$dir/inp" ;;
  cpp) g++ "$file" -o "$base" && "$base" < "$dir/inp" ;;
  cs) mcs "$file" && mono "$base".exe ;;
  go) go build -o "$base" "$file" && "$base" < "$dir/inp" ;;
  java) javac -d classes "$file" && java -cp "$dir/classes" "${base##*/}" < "$dir/inp" ;;
  m) octave "$file" ;;
  py) python "$file" < "$dir/inp" ;;
  [rR]md) Rscript -e "rmarkdown::render('$file', quiet=TRUE)" ;;
  rs) cargo build ;;
  *) sed -n '/^#!/s/^#!//p; q' "$file" | xargs -r -I % "$file" ;;
esac
