#!/bin/sh

# Get selection via dmenu from zathura file history
ZATHURA_HISTORY="$HOME/.local/share/zathura/history"

chosen=$(grep -Po '(?<=\[)/[^]]+' "$ZATHURA_HISTORY" | dmenu -i -l 10 -p "open which book?")

# Exit if none chosen.
[ -z "$chosen" ] && exit

zathura "$chosen"
