#!/bin/sh
# ** requires maim **

IMG_FOLDER=$HOME/pictures/screenshots
IMG_PATH=$IMG_FOLDER/pic-full-"$(date '+%y%m%d-%H%M-%S').png"

#  pause brower media, playerctl needed
playerctl pause
# maim default fullscreen mod, copy to clipboard and save screenshot to IMG_PATH
# -u flag hides cursor
maim -u | tee $IMG_PATH | xclip -selection clipboard  -t image/png

# if quiting maim with ESC, delete empty file.
[ -s $IMG_PATH ] || rm $IMG_PATH

# save screenshot path to file
echo $IMG_PATH > $XDG_DATA_HOME/lastscreenshot
