#!/bin/sh
# ** requires maim **

IMG_PATH=/tmp/maim-tmp-"$(date '+%y%m%d-%H%M-%S').png"

#  pause brower media, playerctl needed
playerctl pause
# maim select mod, copy to clipboard and save to /tmp
# -u flag hides cursor
maim -u -s | tee $IMG_PATH | xclip -selection clipboard  -t image/png
