#!/bin/sh
# ** requires maim and xdotool **

IMG_FOLDER=$HOME/pictures/screenshots
IMG_PATH=$IMG_FOLDER/pic-window-"$(date '+%y%m%d-%H%M-%S').png"

#  pause brower media, playerctl needed
playerctl pause
# take a screenshot of active window, copy to clipboard and save screenshot to IMG_PATH
# -B makes maim also captures the background
# -u flag hides cursor
maim -u -i $(xdotool getactivewindow) -B | tee $IMG_PATH | xclip -selection clipboard  -t image/png

# if quiting maim with ESC, delete empty file.
[ -s $IMG_PATH ] || rm $IMG_PATH

# save screenshot path to file
echo $IMG_PATH > $XDG_DATA_HOME/lastscreenshot
