#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extension or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.
echo
echo "--------------------*** output ***--------------------"
file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

textype() { \
  command="pdflatex"
  ( head -n5 "$file" | grep -qi 'xelatex' ) && command="xelatex"
  $command --output-directory="$dir" "$base" &&
  grep -qi addbibresource "$file" &&
  biber --input-directory "$dir" "$base" &&
  $command --output-directory="$dir" "$base" &&
  $command --output-directory="$dir" "$base"
}

case "$ext" in
  # Try to keep these cases in alphabetical order.
  c) clang "$file" -std=c2x -lm -o "$base" && "$base" ;;
  cpp) clang++ "$file" -std=c++2c -lm -o "$base" && "$base" ;;
  go) go build -o "$base" "$file" && "$base" ;;
  h) sudo make install ;;
  md)
    if  [ -x "$(command -v lowdown)" ]; then
      lowdown --parse-no-intraemph "$file" -Tms | groff -mpdfmark -ms -kept > "$base".pdf
    elif [ -x "$(command -v groffdown)" ]; then
      groffdown -i "$file" | groff > "$base.pdf"
    else
      pandoc -t ms --highlight-style=kate -s -o "$base".pdf "$file"
    fi ; ;;
  py) python "$file" ;;
  rs) cargo run || rustc "$file" && "$base";;
  tex) textype "$file" ;;
  zig) zig build-exe "$file" && "$base" ;;
  *) sed -n '/^#!/s/^#!//p; q' "$file" | xargs -r -I % "$file" ;;
esac
