#!/bin/sh

# This script will compile or run another finishing operation on a document. I
# have this script run via vim.
#
# Compiles .tex. groff (.mom, .ms), .rmd, .md, .org.  Opens .sent files as sent
# presentations. Runs scripts based on extension or shebang.
#
# Note that .tex files which you wish to compile with XeLaTeX should have the
# string "xelatex" somewhere in a comment/command in the first 5 lines.

# pipe file 'inp' into executable
echo
echo "--------------------*** output ***--------------------"
file=$(readlink -f "$1")
dir=${file%/*}
base="${file%.*}"
ext="${file##*.}"

cd "$dir" || exit 1

case "$ext" in
  c) cc "$file" -std=c2x -o "$base" && "$base" < "$dir/inp" ;;
  cpp) g++ "$file" -std=c++23 -o "$base" && "$base" < "$dir/inp" ;;
  go) go build -o "$base" "$file" && "$base" < "$dir/inp" ;;
  py) python "$file" < "$dir/inp" ;;
  rs) cargo run || rustc "$file" && "$base" < "$dir/inp" ;;
  zig) zig build-exe "$file" && "$base" < "$dir/inp" ;;
esac
