#!/bin/sh
set +x

case $(file --mime-type "$(realpath "$1")" -b) in
  application/pdf | application/epub*) zathura "$1" ;;
  text/* | application/json|inode/x-empty) $EDITOR "$1" ;;
  image/*) sxiv "$1" ;;
  audio/*) mpv --audio-display=no "$1" ;;
  video/* | application/vnd.rn-realmedia) mpv "$1" ;;
esac
