#!/bin/sh

# A wmenu binary prompt script.
# Gives a wmenu prompt labeled with $1 to perform command $2.
# For example:
# `./prompt "Do you want to shutdown?" "shutdown -h now"`

[ "$(printf "No\\nYes" | wmenu -i -p "$1" -nb darkred -sb red -sf white -nf gray )" = "Yes" ] && $2
