#!/bin/sh

# usage(the dot is crutial):
# . pyenv [env name]: (create and) activate [env name]
envdir=$HOME/.local/share/pyenv

[ -d $envdir ] || mkdir -p $envdir;

[ -z $1 ] && ls $envdir && exit 0;

# if [env name] not exit, create it.
[ -d $envdir/$1 ] || python -m venv $envdir/$1;

. "$envdir/$1/bin/activate"

echo "if the venv is not activated, check if you ran this script by '. pyenv [env name]'"
