#!/bin/sh

# usage(the dot is crutial):
# . pyenv [env name]: (create and) activate [env name]
VENV_DIR=${PYTHON_VENV_DIR:="$HOME/.local/share/pyenv"}

[ -d $VENV_DIR ] || mkdir -p $VENV_DIR;

# with no arg provided, list all exist virtual envs
[ -z $1 ] && ls $VENV_DIR&& exit 0;

# if [env name] not exit, create it.
[ -d $VENV_DIR/$1 ] || python -m venv $VENV_DIR/$1;

source "$VENV_DIR/$1/bin/activate"
alias venvdir="cd $VENV_DIR/$1"

echo "[*] swicthed to python venv '$1',"
echo "[*] use 'venvdir' to cd into it, use 'deactivate' to leave"
echo "[*] if the venv is not activated, check if you ran this script by"
echo "[*] '. pyenv [env name]'"
