#!/bin/sh

# Podboat sucks. This script replaces it.
# It reads the newsboat queue, queuing downloads with taskspooler.
# It also removes the junk from extensions.
queuefile="$XDG_DATA_HOME/newsboat/queue"

while read -r line; do
  [ -z "$line" ] && continue
  url="${line%%[\t ]*}"
  qndl "$url" "curl -LO"
done < "$queuefile"

echo > "$queuefile"
