#!/bin/sh

# set random wallpaer from directory %bgdir

# Location of link to wallpaper link.
base="$XDG_DATA_HOME/bg"
bgloc=$base
bgdir="$HOME/pictures/wallpapers/likes"

# Configuration files of applications that have their themes changed by pywal.
dunstconf="$XDG_CONFIG_HOME/dunst/dunstrc"
zathuraconf="$XDG_CONFIG_HOME/zathura/zathurarc"

trueloc="$(readlink -f "$bgdir")"
ln -sf "$(find "$trueloc" -iregex '.*.\(jpg\|jpeg\|png\|gif\)' -type f | shuf -n 1)" "$bgloc" && notify-send -i "$bgloc" "Random Wallpaper chosen."

# If pywal is installed, use it.
if command -v wal >/dev/null 2>&1 ; then
  wal -i "$(readlink -f $bgloc)" -o "$XDG_CONFIG_HOME/wal/postrun" >/dev/null 2>&1
# If pywal is removed, return config files to normal.
else
  [ -f "$dunstconf.bak" ] && unlink "$dunstconf" && mv "$dunstconf.bak" "$dunstconf"
  [ -f "$zathuraconf.bak" ] && unlink "$zathuraconf" && mv "$zathuraconf.bak" "$zathuraconf"
fi

feh --bg-fill $base
