#!/bin/sh

# Open a terminal window in the same directory as the currently active window.

PID="$(hyprctl activewindow -j | jq -r .pid)"
PID="$(pstree -lpA "$PID")"
PID="${PID##*"${SHELL##*/}"(}"
PID="${PID#*lf(}"
PID="${PID%%)*}"
cd "$(readlink /proc/"$PID"/cwd)" || return 1
"${TERMINAL:-kitty}"
