#!/bin/sh
xrandr --output eDP1 --off --output DP1 --primary --mode 3840x2160 --pos 0x0 --rotate normal --dpi 300 --output DP2 --off --output HDMI1 --off --output HDMI2 --off --output VIRTUAL1 --off && setbg
