#!/bin/sh

# A dmenu wrapper script for system functions.
export WM="dwm"
case "$(readlink -f /sbin/init)" in
  *systemd*) ctl='systemctl' ;;
  *) ctl='loginctl' ;;
esac

wmpid(){ # This function is needed if there are multiple instances of the window manager.
  tree="$(pstree -ps $$)"
  tree="${tree#*$WM(}"
  echo "${tree%%)*}"
}

case "$(printf "🎩 htop\n🔒 blurlock\n🚪 leave $WM\n🌀 renew $WM\n💤 sleep\n🔃 reboot\n🔚 shutdown\n📺 display off\n" | dmenu -i -p 'Action: ')" in
  '🎩 htop') st htop ;;
  '🔒 blurlock') blurlock ;;
  "🚪 leave $WM") kill -TERM "$(wmpid)" ;;
  "🌀 renew $WM") kill -HUP "$(wmpid)" ;;
  '💤 sleep') blurlock $ctl suspend -i ;;
  '🔃 reboot') $ctl reboot -i ;;
  '🔚 shutdown') $ctl poweroff -i ;;
  '📺 display off') xset dpms force off ;;
  *) exit 1 ;;
esac
