#!/bin/sh
# timer [any command]

temp=$(mktemp --suffix='.timer')
started=$(date)
read up rest </proc/uptime; t1="${up%.*}${up#*.}"
$@; # ignore failure
read up rest </proc/uptime; t2="${up%.*}${up#*.}"
finished=$(date)
millisec=$(( 10*(t2-t1) ))

echo "$@" > $temp
echo "started  $started" >> $temp
echo "finished $finished" >> $temp
echo "total    $millisec ms" >> $temp

echo
echo "*** command finished ***"
echo "[*] details saved in $temp:"
cat $temp
