#!/bin/sh

# The famous "get a menu of emojis to copy" script.

# Get user selection via wmenu from the emoji file plus the generated
# token-logo list (see build-crypto-emoji-font).
chosen=$(cut -d ';' -f1 ~/.local/share/emoji ~/.local/share/crypto-emoji/picker 2>/dev/null |
  wmenu -i -l 30 | sed "s/ .*//")

# Exit if none chosen.
[ -z "$chosen" ] && exit

# If you run this command with an argument, it will automatically insert the
# character. Otherwise, show a message that the emoji has been copied.
if [ -n "$1" ]; then
  wtype "$chosen"
else
  printf "$chosen" | wl-copy
  notify-send "'$chosen' copied to clipboard." &
fi
