#!/bin/sh

# Usage:
# `$0`: Ask for recording type via wmenu
# `$0 screencast`: Record both audio and screen
# `$0 video`: Record only screen
# `$0 audio`: Record only audio
# `$0 kill`: Kill existing recording
#
# If there is already a running instance, user will be prompted to end it.

save_to=$HOME/videos/records

updateicon() { \
  echo "$1" > /tmp/recordingicon
  barsig 9
}

killrecording() {
  recpid="$(cat /tmp/recordingpid)"
  # kill with SIGTERM, allowing finishing touches.
  kill -15 "$recpid"
  rm -f /tmp/recordingpid
  updateicon ""
  # even after SIGTERM, the recorder may still run, so SIGKILL it.
  sleep 3
  kill -9 "$recpid" 2>/dev/null
  exit
}

screencast() { \
  wf-recorder -a \
  -f "$save_to/screencast-$(date '+%y%m%d-%H%M-%S').mp4" &
  echo $! > /tmp/recordingpid
  updateicon "⏺️ 🎙️"
}

video() { \
  wf-recorder \
  -f "$save_to/video-$(date '+%y%m%d-%H%M-%S').mp4" &
  echo $! > /tmp/recordingpid
  updateicon "⏺️ "
}

webcamhidef() { ffmpeg \
  -f v4l2 \
  -i /dev/video0 \
  -video_size 1920x1080 \
  "$save_to/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
  echo $! > /tmp/recordingpid
  updateicon "🎥"
}

webcam() { ffmpeg \
  -f v4l2 \
  -i /dev/video0 \
  -video_size 640x480 \
  "$save_to/webcam-$(date '+%y%m%d-%H%M-%S').mkv" &
  echo $! > /tmp/recordingpid
  updateicon "🎥"
}


audio() { \
  ffmpeg \
  -f alsa -i default \
  -c:a flac \
  "$save_to/audio-$(date '+%y%m%d-%H%M-%S').flac" &
  echo $! > /tmp/recordingpid
  updateicon "🎙️"
}

askrecording() { \
  choice=$(printf "screencast\\nvideo\\nvideo selected\\naudio\\nwebcam\\nwebcam (hi-def)" | wmenu -i -p "Select recording style:")
  case "$choice" in
    screencast) screencast;;
    audio) audio;;
    video) video;;
    *selected) videoselected;;
    webcam) webcam;;
    "webcam (hi-def)") webcamhidef;;
  esac
}

asktoend() { \
  response=$(printf "No\\nYes" | wmenu -i -p "Recording still active. End recording?") &&
  [ "$response" = "Yes" ] &&  killrecording
}

videoselected()
{
  wf-recorder -g "$(slurp)" \
  -f "$save_to/box-$(date '+%y%m%d-%H%M-%S').mp4" &
  echo $! > /tmp/recordingpid
  updateicon "⏺️ "
}

case "$1" in
  screencast) screencast;;
  audio) audio;;
  video) video;;
  *selected) videoselected;;
  kill) killrecording;;
  *) ([ -f /tmp/recordingpid ] && asktoend && exit) || askrecording;;
esac
